# Generated by Django 5.0.3 on 2024-04-03 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postphoto',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post', verbose_name='Пост'),
        ),
    ]
